controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
admin.voyage.suppr:
    path: /admin/voyages/suppr/{id}
    controller: App\Controller\admin\AdminVoyagesController::suppr  
    
admin.voyage.edit:
    path: /admin/voyages/edit/{id}
    controller: App\Controller\admin\AdminVoyagesController::edit

voyages.showone:
    path: /voyages/showone/{id}
    controller: App\Controller\VoyagesController::showone        

admin.voyages:
    path: /admin
    controller: App\Controller\admin\AdminVoyagesController::index
    
admin.environnement.supp:
    path: /admin/environnement/suppr/{id}
    controller: App\Controller\admin\AdminEnvironnementController::suppr    
     
ajout.environnement:
    path: /admin/environnement/ajout
    controller: App\Controller\Admin\EnvironnementController::ajout
 
admin.environnements:
    path: /admin/environnements
    controller: App\Controller\AdminController::environnements
   

voyages_showone:
    path: /voyages/voyage/{id}
    controller: App\Controller\admin\VoyageController::showOne
    