controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

voyages.showone:
    path: /voyages/showone/{id}
    controller: App\Controller\VoyagesController::showone
    
    
    
admin.voyage.edit:
    path: /admin/voyages/edit/{id}
    controller: App\Controller\admin\AdminVoyagesController::edit
    
admin.voyages:
    path: /admin
    controller: App\Controller\admin\AdminVoyagesController::index
    
    